### ISSUE TITLE
C-c bindings in colorful-mode-map

### ISSUE THREAD

**Issue by jumper047** [DevelopmentCool2449/colorful-mode#1]
Hi, according to [Emacs Key Bindings Convention](ww.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html):
> Don’t define C-c letter as a key in Lisp programs. Sequences consisting of C-c and a letter (either upper or lower case; ASCII or non-ASCII) are reserved for users; they are the only sequences reserved for users, so do not block them.

**Comment by DevelopmentCool2449** [comment]
Hi, Thank you for the advice, that was my doubt I had when I was making the bindings because there are other packages that also bind to C-c.

I've now changed the key prefix.
