### ISSUE TITLE
Looking for a maintainer

### ISSUE THREAD

**Issue by DevelopmentCool2449** [DevelopmentCool2449/colorful-mode#10]
As explained at this [toot](https://emacs.ch/@DevelopmentCool2449/112759309585244756) i'm currently unable to still developing and maintaining this package.

Since this package is available at GNU ELPA (which it was the best decision that i did) the new maintainer need to have already their copyright assigment paperwork done.

In case the source code needs to be explained, i will be available (i hope) to help.

I hope that you all can understand the current situation i'm going through.

Thanks.

**Comment by jcs090218** [comment]
I can help maintain this package since I enjoyed using this package a lot!

I'm sorry about what you have lost. File recovery is always hard and unexpected. :( I hope you can come back to the Emacs community as soon as you get everything back on track!

**Comment by DevelopmentCool2449** [comment]
Thank you for your interest, I can trust that this will be in good hands.

Would you like if i transfer the repository ownership to you?

**Comment by jcs090218** [comment]
> Would you like if i transfer the repository ownership to you?

Sure, if you want to. I Or you can just add me as a outside collaborator. Both works for me. :)

**Comment by DevelopmentCool2449** [comment]
Fine, i think that add you as collaborator would be better since transfering ownership can conflict with GNU ELPA and break straight/vc users configurations.

Thank you.

**Comment by DevelopmentCool2449** [comment]
Fine, i think that add you as collaborator would be better since transfering ownership can conflict with GNU ELPA and break straight/vc users configurations.

Thank you.
