### ISSUE TITLE
Color Palette prefix used in demo screenshots

### ISSUE THREAD

**Issue by AnweshGangula** [DevelopmentCool2449/colorful-mode#3]
Hi,

can you please provide the code for the color palette icon used for prefix in the demo screenshot?

![demo screenshot](https://raw.githubusercontent.com/DevelopmentCool2449/colorful-mode/main/assets/screenshot3.png)

**Comment by DevelopmentCool2449** [comment]
Sure
```elisp
(setq colorful-prefix-string (concat (nerd-icons-faicon "nf-fae-palette_color") " "))
```

**Comment by AnweshGangula** [comment]
I'm getting the following error: 

> Symbol's function definition is void: nerd-icons-faicon

**Comment by DevelopmentCool2449** [comment]
You need to install [nerd-icons.el](https://github.com/rainstormstudio/nerd-icons.el) package and/or use a [patched nerd font](https://www.nerdfonts.com/font-downloads)

Also you can use this:

```elisp
(setq colorful-prefix-string " ")
```

**Comment by AnweshGangula** [comment]
I installed both nerd-icons and one of the patched nerd fonts you mentioned, but still get the same error.

I also am not able to see the icons you added in the above response - `(setq colorful-prefix-string " ")`

**Comment by DevelopmentCool2449** [comment]
I can't help so much since this feels more an issue with `nerd-icons.el`
but this can help,
try install `Symbols Nerd Fonts Mono` font and ensure your emacs is using a patched nerd font (not `Symbols Nerd Fonts Mono`).

and then use this in your config:

```elisp
(setq colorful-prefix-string " ")
;; or tihs
(setq colorful-prefix-string (concat (nerd-icons-faicon "nf-fae-palette_color") " "))
```

**Comment by AnweshGangula** [comment]
I was trying to figure out the issue but couldn't. Although, I can see that when I execute the command with `insert` I get the icon propery, but when I execute with `concat` the result is not rendered properly

Is this expected or does this mean I have some issue?

## using `result`
```lisp
(insert (nerd-icons-faicon "nf-fae-palette_color") " ")
```
![result command output](https://github.com/DevelopmentCool2449/colorful-mode/assets/22996896/ae9ee972-7fc2-4423-8cbe-5506b8605578)

## using `concat`

```lisp
(concat (nerd-icons-faicon "nf-fae-palette_color") " ")
```
![concat result](https://github.com/DevelopmentCool2449/colorful-mode/assets/22996896/dc24ae22-f978-4441-84c4-79256f4eb2ca)

**Comment by AnweshGangula** [comment]
I tried switching the font-family to a couple of other families to see if this works, but I still get the error `Symbol's function definition is void: nerd-icons-faicon`.

I also asked for what the issue could be in this [superuser post](Symbol's function definition is void: nerd-icons-faicon) and found that the icon might be specific to a font. So maybe this particular icon needs a specific font family?

**Comment by DevelopmentCool2449** [comment]
> I was trying to figure out the issue but couldn't.
> 
> Can you help me with what you mean by patched nerd font? And how can is use that? - because I tried using (nerd-icons-font-family "Source Code Pro"), but all the icons went away

`nerd-icons-font-family` must be set to a downloaded font from nerd font webpage.
it's optional setting it.

> I can see that when I execute this command (C-c C-c) with insert I get the icon properly, but when I execute with concat the result is not rendered properly
> 
> Is this expected or does this mean I have some issue?

it's an issue, you should probably use this in your early-init.el `(prefer-coding-system 'utf-8)`

> and found that the icon might be specific to a font. So maybe this particular icon needs a specific font family?

It's not necessarily, nerd font already provides all the icons for this.

> Ignoring the font, the first issue to fix in my case is the `Symbol's function definition is void: nerd-icons-faicon` - which i'm not sure what I'm doing wrong
> I tried switching the font-family to a couple of other families to see if this works, but I still get the error `Symbol's function definition is void: nerd-icons-faicon`.

You probably must use `(require 'nerd-icons)` in your config (or add the `:demand t` keyword if you use `use-package`)

**Comment by AnweshGangula** [comment]
tried the `early-init` & `:demant t` approach you mentioned, still doesn't fix the issue. I raised an issue in the nerd-icons repo.
And Thank you for your help @DevelopmentCool2449. Really appreciate you taking the time.
