### ISSUE TITLE
enable colorful-mode in specified modes

### ISSUE THREAD

**Issue by seagle0128** [DevelopmentCool2449/colorful-mode#5]
https://github.com/DevelopmentCool2449/colorful-mode/blob/cc94056fea3457f6e40c0c4ac8b9569de9c1f47e/colorful-mode.el#L769-L771

IMO, it's better make the predicate modes customizable in `global-colorful-mode`.

**Comment by DevelopmentCool2449** [comment]
As far as i know it's already customizable, you can check `global-colorful-modes` option.

**Comment by seagle0128** [comment]
Yep, but `global-colorful-modes` is just used in `turn-on-colorful-mode`, while not in `global-colorful-mode`.

**Comment by seagle0128** [comment]
I didn't see the `global-colorful-modes` option in the codes. Just this

```elisp
;; Silence a byte-compile warning about global-colorful-modes not
;; being defined, if anyone knows why this happens please send a
;; patch.
(defvar global-colorful-modes)
```

**Comment by DevelopmentCool2449** [comment]
`global-colorful-modes` is automatically defined by macro `define-globalized-minor-mode`
```elisp
   (unless colorful-mode
     (colorful-mode t)))

 ;;;###autoload
 (define-globalized-minor-mode global-colorful-mode
   colorful-mode turn-on-colorful-mode
   :predicate '(mhtml-mode html-ts-mode latex-mode prog-mode))
```

**Comment by seagle0128** [comment]
Okay, then I am closing it.
